version: "3"

services:
  client:
    stdin_open: true
    container_name: aggie-reuse-ui
    build: ./server/client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - aggie-reuse

  server:
    build: ./server
    container_name: aggie-reuse-api
    env_file: docker.env
    ports:
      - "5000:5000"
    networks:
      - aggie-reuse
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    container_name: aggie-reuse-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aggie_reuse_inventory
    ports:
      - "5432:5432"
    networks:
      - aggie-reuse
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  aggie-reuse:
    driver: bridge
